# Type stubs for kivymd.uix.dialog
from typing import Any, Optional
from kivy.uix.widget import Widget

class MDDialog(Widget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def open(self) -> None: ...
    def dismiss(self) -> None: ...

class MDDialogHeadlineText(Widget):
    text: str
    def __init__(self, **kwargs: Any) -> None: ...

class MDDialogButtonContainer(Widget):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class MDDialogIcon(Widget):
    icon: str
    def __init__(self, **kwargs: Any) -> None: ...