from typing import Any

# Minimal catch-all stubs for Flet used by the project.
# This maps commonly-used names to "Any" so Pyright/Pylance stop reporting
# attribute-access and unknown-member errors. It's intentionally permissive.

AnyType = Any

class Control(Any):
	style: Any
	def update(self) -> None: ...

class Page(Any):
	dialog: Any
	snack_bar: Any
	theme_mode: Any
	def window_close(self) -> None: ...
	def run_task(self, coro: Any, *args: Any, **kwargs: Any) -> Any: ...

class Theme(Any): ...
class Animation(Any): ...
class IconControl(Any): ...
class RowControl(Any): ...
class ContainerControl(Any): ...
class DividerControl(Any): ...
class TextControl(Any): ...

# Common helpers
def run(callable: Any) -> Any: ...

# Export typical names used across the codebase
Colors: Any
Icons: Any
AnimationCurve: Any
ThemeMode: Any

# Button types
class ElevatedButton(Control): ...
class OutlinedButton(Control): ...
class FilledButton(Control): ...
class TextButton(Control): ...
class IconButton(Control): ...

# SnackBar and Dialog
class SnackBar(Control): ...
class Dialog(Control): ...

# State manager used in views
class StateManager(Any):
	def set_progress(self, key: str, value: Any) -> None: ...
	def get(self, key: str, default: Any = None) -> Any: ...
	def subscribe_settings(self, callback: Any) -> None: ...
	def unsubscribe_settings(self, callback: Any) -> None: ...
	def get_state(self, key: str, default: Any = None) -> Any: ...


# Minimal protocol-like ServerBridge used in views/tests
class ServerBridge(Any):
	def get_clients(self) -> list: ...
	def add_client(self, client: Any) -> Any: ...
	def delete_client(self, client_id: Any) -> Any: ...
	def load_settings(self) -> dict: ...
	def save_settings(self, settings: dict) -> Any: ...
	def get_files(self) -> list: ...
	def upload_file(self, file: Any) -> Any: ...
	def disconnect_client(self, client_id: Any) -> Any: ...
	def download_file(self, file_id: Any, destination_path: str) -> Any: ...
	def get_table_data(self, table: str) -> Any: ...
	def get_logs(self) -> Any: ...
	def get_client_files(self, client_id: str) -> Any: ...
	def delete_file(self, file_id: str) -> Any: ...
	def get_database_info(self) -> Any: ...

# Simple casts for constructors
def Icon(*args: Any, **kwargs: Any) -> IconControl: ...
def Text(*args: Any, **kwargs: Any) -> TextControl: ...

# Generic factory/constructor fallback
def __getattr__(name: str) -> Any: ...
