ignore:
  - "vcpkg/**"
  - "tests/**"
  - "**/*.py.git"
  - "**/.mypy_cache/**"
  - "**/.pytest_cache/**"
  - "**/flet_venv/**"
  - "**/.venv/**"
  - "important_docs/**"
  - "docs/**"
  - "storage/**"
  - "**/build/**"
  - "**/dist/**"
  - "**/node_modules/**"
  - "FletV2/main.py"
  - "FletV2/server_adapter.py"
  - "FletV2/test_integration.py"
  - "FletV2/utils/mock_data_generator.py"
  - "final_emoji_test.py"
